const patterns = {
    1: [{ top: "5px", left: "20px", rotate: "-45deg" }],
    2: [
      { top: "8px", left: "20px", rotate: "-45deg" },
      { top: "0px", left: "30px", rotate: "45deg" },
    ],
    3: [
      { top: "8px", left: "20px", rotate: "-45deg" },
      { top: "0px", left: "30px", rotate: "45deg" },
      { top: "8px", left: "40px", rotate: "-45deg" },
    ],
    4: [
      { top: "8px", left: "20px", rotate: "-45deg" },
      { top: "0px", left: "30px", rotate: "45deg" },
      { top: "8px", left: "40px", rotate: "-45deg" },
      { top: "16px", left: "30px", rotate: "45deg" },
    ],
    5: [
      { top: "8px", left: "20px", rotate: "-45deg" },
      { top: "0px", left: "30px", rotate: "45deg" },
      { top: "8px", left: "40px", rotate: "-45deg" },
      { top: "16px", left: "30px", rotate: "45deg" },
      { top: "8px", left: "30px", rotate: "0deg" },
    ],
    6: [
      { top: "8px", left: "20px", rotate: "-45deg" },
      { top: "0px", left: "30px", rotate: "45deg" },
      { top: "8px", left: "40px", rotate: "-45deg" },
      { top: "16px", left: "30px", rotate: "45deg" },
      { top: "8px", left: "30px", rotate: "0deg" },
      { top: "28px", left: "20px", rotate: "-45deg" },
    ],
    7: [
      { top: "8px", left: "20px", rotate: "-45deg" },
      { top: "0px", left: "30px", rotate: "45deg" },
      { top: "8px", left: "40px", rotate: "-45deg" },
      { top: "16px", left: "30px", rotate: "45deg" },
      { top: "8px", left: "30px", rotate: "0deg" },
      { top: "30px", left: "20px", rotate: "-45deg" },
      { top: "22px", left: "30px", rotate: "45deg" },
    ],
    8: [
      { top: "8px", left: "20px", rotate: "-45deg" },
      { top: "0px", left: "30px", rotate: "45deg" },
      { top: "8px", left: "40px", rotate: "-45deg" },
      { top: "16px", left: "30px", rotate: "45deg" },
      { top: "8px", left: "30px", rotate: "0deg" },
      { top: "30px", left: "20px", rotate: "-45deg" },
      { top: "22px", left: "30px", rotate: "45deg" },
      { top: "30px", left: "40px", rotate: "-45deg" },
    ],
    9: [
      { top: "8px", left: "20px", rotate: "-45deg" },
      { top: "0px", left: "30px", rotate: "45deg" },
      { top: "8px", left: "40px", rotate: "-45deg" },
      { top: "16px", left: "30px", rotate: "45deg" },
      { top: "8px", left: "30px", rotate: "0deg" },
      { top: "30px", left: "20px", rotate: "-45deg" },
      { top: "22px", left: "30px", rotate: "45deg" },
      { top: "30px", left: "40px", rotate: "-45deg" },
      { top: "40px", left: "30px", rotate: "45deg" },
    ],
    10: [
      { top: "8px", left: "20px", rotate: "-45deg" },
      { top: "0px", left: "30px", rotate: "45deg" },
      { top: "8px", left: "40px", rotate: "-45deg" },
      { top: "16px", left: "30px", rotate: "45deg" },
      { top: "8px", left: "30px", rotate: "0deg" },
      { top: "30px", left: "20px", rotate: "-45deg" },
      { top: "22px", left: "30px", rotate: "45deg" },
      { top: "30px", left: "40px", rotate: "-45deg" },
      { top: "40px", left: "30px", rotate: "45deg" },
      { top: "30px", left: "30px", rotate: "0deg" },
    ],
    11: [
      { top: "8px", left: "20px", rotate: "-45deg" },
      { top: "0px", left: "30px", rotate: "45deg" },
      { top: "8px", left: "40px", rotate: "-45deg" },
      { top: "16px", left: "30px", rotate: "45deg" },
      { top: "8px", left: "30px", rotate: "0deg" },
      { top: "30px", left: "20px", rotate: "-45deg" },
      { top: "22px", left: "30px", rotate: "45deg" },
      { top: "30px", left: "40px", rotate: "-45deg" },
      { top: "40px", left: "30px", rotate: "45deg" },
      { top: "30px", left: "30px", rotate: "0deg" },
      { top: "50px", left: "20px", rotate: "-45deg" },
    ],
    12: [
      { top: "8px", left: "20px", rotate: "-45deg" },
      { top: "0px", left: "30px", rotate: "45deg" },
      { top: "8px", left: "40px", rotate: "-45deg" },
      { top: "16px", left: "30px", rotate: "45deg" },
      { top: "8px", left: "30px", rotate: "0deg" },
      { top: "30px", left: "20px", rotate: "-45deg" },
      { top: "22px", left: "30px", rotate: "45deg" },
      { top: "30px", left: "40px", rotate: "-45deg" },
      { top: "40px", left: "30px", rotate: "45deg" },
      { top: "30px", left: "30px", rotate: "0deg" },
      { top: "52px", left: "20px", rotate: "-45deg" },
      { top: "44px", left: "30px", rotate: "45deg" },
    ],
    13: [
      { top: "8px", left: "20px", rotate: "-45deg" },
      { top: "0px", left: "30px", rotate: "45deg" },
      { top: "8px", left: "40px", rotate: "-45deg" },
      { top: "16px", left: "30px", rotate: "45deg" },
      { top: "8px", left: "30px", rotate: "0deg" },
      { top: "30px", left: "20px", rotate: "-45deg" },
      { top: "22px", left: "30px", rotate: "45deg" },
      { top: "30px", left: "40px", rotate: "-45deg" },
      { top: "40px", left: "30px", rotate: "45deg" },
      { top: "30px", left: "30px", rotate: "0deg" },
      { top: "52px", left: "20px", rotate: "-45deg" },
      { top: "44px", left: "30px", rotate: "45deg" },
      { top: "52px", left: "40px", rotate: "-45deg" },
    ],
    14: [
      { top: "8px", left: "20px", rotate: "-45deg" },
      { top: "0px", left: "30px", rotate: "45deg" },
      { top: "8px", left: "40px", rotate: "-45deg" },
      { top: "16px", left: "30px", rotate: "45deg" },
      { top: "8px", left: "30px", rotate: "0deg" },
      { top: "30px", left: "20px", rotate: "-45deg" },
      { top: "22px", left: "30px", rotate: "45deg" },
      { top: "30px", left: "40px", rotate: "-45deg" },
      { top: "40px", left: "30px", rotate: "45deg" },
      { top: "30px", left: "30px", rotate: "0deg" },
      { top: "52px", left: "20px", rotate: "-45deg" },
      { top: "44px", left: "30px", rotate: "45deg" },
      { top: "52px", left: "40px", rotate: "-45deg" },
      { top: "60px", left: "30px", rotate: "45deg" },
    ],
    15: [
      { top: "8px", left: "20px", rotate: "-45deg" },
      { top: "0px", left: "30px", rotate: "45deg" },
      { top: "8px", left: "40px", rotate: "-45deg" },
      { top: "16px", left: "30px", rotate: "45deg" },
      { top: "8px", left: "30px", rotate: "0deg" },
      { top: "30px", left: "20px", rotate: "-45deg" },
      { top: "22px", left: "30px", rotate: "45deg" },
      { top: "30px", left: "40px", rotate: "-45deg" },
      { top: "40px", left: "30px", rotate: "45deg" },
      { top: "30px", left: "30px", rotate: "0deg" },
      { top: "52px", left: "20px", rotate: "-45deg" },
      { top: "44px", left: "30px", rotate: "45deg" },
      { top: "52px", left: "40px", rotate: "-45deg" },
      { top: "60px", left: "30px", rotate: "45deg" },
      { top: "52px", left: "30px", rotate: "0deg" },
    ],
  };

export default patterns;